version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=coachpro
      - POSTGRES_PASSWORD=Sridevi@95
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=coachpro
      - POSTGRES_PASSWORD=Sridevi@95
    depends_on:
      - db